version: "3.9"

services:
  database:
    image: postgres:16.0-alpine3.18
    container_name: database
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  app:
    build: .
    restart: on-failure
    depends_on:
      - database
    command: "./docker/startup.sh"

volumes:
  database: