default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432
  
development:
  <<: *default
  database: <%= ENV["POSTGRES_NAME"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_NAME"] %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["POSTGRES_NAME"] %>
  cache:
    <<: *primary_production
    database: kamal_demo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kamal_demo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kamal_demo_production_cable
    migrations_paths: db/cable_migrate