service: kamal_demo

image: ningchang1995/kamal_demo

servers:
  web:
    - 167.172.95.239

proxy:
  ssl: true
  host: 167.172.95.239
  app_port: 3000

registry:
  username: ningchang1995
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_USERNAME
    - POSTGRES_PASSWORD
  clear:
    POSTGRES_HOST: 167.172.95.239
    POSTGRES_NAME: kamal_demo-postgres


accessories:
  db:
    image: postgres:13
    host: 167.172.95.239
    port: "5432"
    env:
      clear:
        POSTGRES_NAME: "kamal_demo-postgres"
        POSTGRES_HOST: 167.172.95.239
      secret:
        - POSTGRES_USERNAME
        - POSTGRES_PASSWORD
        - POSTGRES_HOST
    directories:
      - data:/var/lib/postgresql/data